#!/bin/bash

echo "🔍 Checking Docker File Sharing Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Required path for Docker to access:"
echo "  /Applications/XAMPP/xamppfiles/htdocs/projects/seelaan/onlinejobs/backend-v7"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 MANUAL CHECK REQUIRED:"
echo ""
echo "1. Open Docker Desktop"
echo "2. Click Settings (gear icon)"
echo "3. Click 'Resources' → 'File Sharing'"
echo "4. Look for this EXACT path in the list:"
echo ""
echo "   /Applications/XAMPP/xamppfiles/htdocs/projects/seelaan/onlinejobs/backend-v7"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If the path is NOT there:"
echo ""
echo "  a) Click the '+' button"
echo "  b) Type or paste:"
echo "     /Applications/XAMPP/xamppfiles/htdocs/projects/seelaan/onlinejobs/backend-v7"
echo "  c) Press Enter"
echo "  d) Click 'Apply & Restart' (bottom right)"
echo "  e) Wait for Docker to restart (check 'Engine running' in bottom bar)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Alternative: Add parent directory (more flexible):"
echo "  /Applications/XAMPP/xamppfiles/htdocs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After adding and restarting, test with:"
echo "  docker compose up -d"
echo ""

